language: python

python:
  - 2.7.9

sudo: false

branches:
  except:
    - master

env:
  - TRAVIS_NODE_VERSION="5.6.0"

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g grunt-cli
  - npm install -g bower
  - cd .build && npm install --quiet && bower install && cd ..

install:
    - python setup.py install

script:
  - cd .build && grunt travis && cd ..
  - python setup.py test

cache:
  directories:
    - $HOME/.cache/pip
    - .build/bower_components
    - .build/node_modules

after_failure:
  - cat ./Logs/sickrage.log

notifications:
  irc: "irc.freenode.net#sickrage-builds"
  email:
    on_success: change
    on_failure: change
